### PR TITLE
Fix 131 migration grading conflicts

### PR DESCRIPTION
**Pull request by grobalex**
Migration for creating the grading_conflicts table

Please review for completeness / correctness

### CODE REVIEW

**Comment by kylesferrazza** [comment]
The standard is to name the file `{datestring}_create_grading_conflicts` and the class `CreateGradingConflicts`

**Comment by blerner** [comment]
This is typically done by `rails generate migration CreateGradingConflicts`.  The filename will then be timestamped, so that running `rake db:migrate` will apply the migrations in the correct order.

**Comment by grobalex** [comment]
Fixed; Added the "create" part to the filename and class name

**Comment by blerner** [comment]
This is now outdated; we've implemented grading conflicts in https://github.com/CodeGrade/bottlenose/pull/227.

**Pull request closed without merging**
